export const data = [
    {
        "id": 1,
        "userID": 1,
        "title": "wef",
        "description": "gew",
        "prep_time": "ewf",
        "total_time": "fwe",
        "ingredients": "[{\"name\":\"ingredients-0\",\"value\":\"gwe\"}]",
        "instructions": "gew",
        "images": null,
        "nutritional": "{\"servings\":\"gew\",\"servingSize\":\"wh\",\"calories\":\"gwe\"}",
        "created_at": "2022-04-16T23:58:13.000000Z",
        "updated_at": "2022-04-16T23:58:13.000000Z"
    },
    {
        "id": 2,
        "userID": 1,
        "title": "214",
        "description": "her",
        "prep_time": "nbntyn",
        "total_time": "nt",
        "ingredients": "[{\"name\":\"ingredients-0\",\"value\":\"nye\"}]",
        "instructions": "ytymt",
        "images": null,
        "nutritional": "{\"servings\":\"rt\",\"servingSize\":\"werye\",\"calories\":\"erttr\"}",
        "created_at": "2022-04-16T23:58:25.000000Z",
        "updated_at": "2022-04-16T23:58:25.000000Z"
    },
    {
        "id": 3,
        "userID": 1,
        "title": "asfggas",
        "description": "bwe",
        "prep_time": "ewt",
        "total_time": "gew",
        "ingredients": "[{\"name\":\"ingredients-0\",\"value\":\"ewg\"}]",
        "instructions": "bre",
        "images": null,
        "nutritional": "{\"servings\":\"ber\",\"servingSize\":\"weewtw\",\"calories\":\"ber\"}",
        "created_at": "2022-04-17T01:10:58.000000Z",
        "updated_at": "2022-04-17T01:10:58.000000Z"
    },
    {
        "id": 4,
        "userID": 2,
        "title": "wef",
        "description": "gew",
        "prep_time": "ewf",
        "total_time": "fwe",
        "ingredients": "[{\"name\":\"ingredients-0\",\"value\":\"gwe\"}]",
        "instructions": "gew",
        "images": null,
        "nutritional": "{\"servings\":\"gew\",\"servingSize\":\"wh\",\"calories\":\"gwe\"}",
        "created_at": "2022-04-16T23:58:13.000000Z",
        "updated_at": "2022-04-16T23:58:13.000000Z"
    },
    {
        "id": 5,
        "userID": 2,
        "title": "214",
        "description": "her",
        "prep_time": "nbntyn",
        "total_time": "nt",
        "ingredients": "[{\"name\":\"ingredients-0\",\"value\":\"nye\"}]",
        "instructions": "ytymt",
        "images": null,
        "nutritional": "{\"servings\":\"rt\",\"servingSize\":\"werye\",\"calories\":\"erttr\"}",
        "created_at": "2022-04-16T23:58:25.000000Z",
        "updated_at": "2022-04-16T23:58:25.000000Z"
    },
    {
        "id": 6,
        "userID": 1,
        "title": "asfggas 6",
        "description": "bwe",
        "prep_time": "ewt",
        "total_time": "gew",
        "ingredients": "[{\"name\":\"ingredients-0\",\"value\":\"ewg\"}]",
        "instructions": "bre",
        "images": null,
        "nutritional": "{\"servings\":\"ber\",\"servingSize\":\"weewtw\",\"calories\":\"ber\"}",
        "created_at": "2022-04-17T01:10:58.000000Z",
        "updated_at": "2022-04-17T01:10:58.000000Z"
    }
]